config/routes.rb
DevEvent::Application.routes.draw do
  resources :health_checks

  resources :test_events

  get "process_test_event_queue" => "test_events#process_test_event_queue", :as => "process_test_event_queue"
  get "health_check_sqs" => "health_checks#health_check_sqs", :as => "health_check_sqs"
  root :to => "test_events#process_test_event_queue"

end

app/controllers/health_checks_controller.rb
class HealthChecksController < ApplicationController
  # GET /health_checks
  # GET /health_checks.json
  @approximate_number_of_messages=3
  helper_method :health_check_sqs
  def health_check_sqs
    health_checked = AwsSqs.health_check('event',3)
    puts "HEALTH CHECK FOR event QUEUE  is === #{health_checked}"
    if health_checked
      head 200
      puts "HEAD 200"
    else

      head 200
      puts "HEAD 500 Try restating the test_events_controller for polling messages"
      testEventsController = TestEventsController.new
      testEventsController.process_test_event_queue


    end
  end
end

app/helpers/health_checks_helper.rb
module HealthChecksHelper
end

app/views/health_checks/_form.html.erb
<%= form_for(@health_check) do |f| %>
  <% if @health_check.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@health_check.errors.count, "error") %> prohibited this health_check from being saved:</h2>

      <ul>
      <% @health_check.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/health_checks/edit.html.erb
<h1>Editing health_check</h1>

<%= render 'form' %>

<%= link_to 'Show', @health_check %> |
<%= link_to 'Back', health_checks_path %>

app/views/health_checks/index.html.erb
<h1>Listing event_processes</h1>

<table>
  <tr>
    <%=  health_check_sqs %>

    <th></th>
    <th></th>
    <th></th>
  </tr>


</table>

app/views/health_checks/new.html.erb
<h1>New health_check</h1>

<%= render 'form' %>

<%= link_to 'Back', health_checks_path %>

app/views/health_checks/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_health_check_path(@health_check) %> |
<%= link_to 'Back', health_checks_path %>